"""+price in orderitem

Revision ID: 091cf724bfaf
Revises: 123584ab1166
Create Date: 2025-11-14 23:44:54.276016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091cf724bfaf'
down_revision: Union[str, Sequence[str], None] = '123584ab1166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.Float()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###
